[package]
name = "lan_backup"
version = "0.1.0"
edition = "2024"

[dependencies]
walkdir = "2"
ssh2 = "0.9"
dotenv = "0.15.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

blake3 = "1.5"
